// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFilmDurationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilmId        int32                  `protobuf:"varint,1,opt,name=filmId,proto3" json:"filmId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilmDurationReq) Reset() {
	*x = GetFilmDurationReq{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilmDurationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilmDurationReq) ProtoMessage() {}

func (x *GetFilmDurationReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilmDurationReq.ProtoReflect.Descriptor instead.
func (*GetFilmDurationReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetFilmDurationReq) GetFilmId() int32 {
	if x != nil {
		return x.FilmId
	}
	return 0
}

type GetFilmDurationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilmDuration  string                 `protobuf:"bytes,1,opt,name=filmDuration,proto3" json:"filmDuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilmDurationRes) Reset() {
	*x = GetFilmDurationRes{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilmDurationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilmDurationRes) ProtoMessage() {}

func (x *GetFilmDurationRes) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilmDurationRes.ProtoReflect.Descriptor instead.
func (*GetFilmDurationRes) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetFilmDurationRes) GetFilmDuration() string {
	if x != nil {
		return x.FilmDuration
	}
	return ""
}

type GetPriceOfFABReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FABId         int32                  `protobuf:"varint,1,opt,name=fABId,proto3" json:"fABId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceOfFABReq) Reset() {
	*x = GetPriceOfFABReq{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceOfFABReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceOfFABReq) ProtoMessage() {}

func (x *GetPriceOfFABReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceOfFABReq.ProtoReflect.Descriptor instead.
func (*GetPriceOfFABReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *GetPriceOfFABReq) GetFABId() int32 {
	if x != nil {
		return x.FABId
	}
	return 0
}

type GetPriceOfFABRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         int32                  `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceOfFABRes) Reset() {
	*x = GetPriceOfFABRes{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceOfFABRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceOfFABRes) ProtoMessage() {}

func (x *GetPriceOfFABRes) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceOfFABRes.ProtoReflect.Descriptor instead.
func (*GetPriceOfFABRes) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *GetPriceOfFABRes) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CheckFABExistReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FABId         int32                  `protobuf:"varint,1,opt,name=fABId,proto3" json:"fABId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFABExistReq) Reset() {
	*x = CheckFABExistReq{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFABExistReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFABExistReq) ProtoMessage() {}

func (x *CheckFABExistReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFABExistReq.ProtoReflect.Descriptor instead.
func (*CheckFABExistReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *CheckFABExistReq) GetFABId() int32 {
	if x != nil {
		return x.FABId
	}
	return 0
}

type CheckFABExistRes struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResponseMessage string                 `protobuf:"bytes,1,opt,name=responseMessage,proto3" json:"responseMessage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckFABExistRes) Reset() {
	*x = CheckFABExistRes{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFABExistRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFABExistRes) ProtoMessage() {}

func (x *CheckFABExistRes) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFABExistRes.ProtoReflect.Descriptor instead.
func (*CheckFABExistRes) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *CheckFABExistRes) GetResponseMessage() string {
	if x != nil {
		return x.ResponseMessage
	}
	return ""
}

type GetFilmReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilmId        int32                  `protobuf:"varint,1,opt,name=filmId,proto3" json:"filmId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilmReq) Reset() {
	*x = GetFilmReq{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilmReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilmReq) ProtoMessage() {}

func (x *GetFilmReq) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilmReq.ProtoReflect.Descriptor instead.
func (*GetFilmReq) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *GetFilmReq) GetFilmId() int32 {
	if x != nil {
		return x.FilmId
	}
	return 0
}

type GetFilmRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilmId        int32                  `protobuf:"varint,1,opt,name=filmId,proto3" json:"filmId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	PosterUrl     string                 `protobuf:"bytes,5,opt,name=posterUrl,proto3" json:"posterUrl,omitempty"`
	Genres        string                 `protobuf:"bytes,6,opt,name=genres,proto3" json:"genres,omitempty"`
	Duration      string                 `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilmRes) Reset() {
	*x = GetFilmRes{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilmRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilmRes) ProtoMessage() {}

func (x *GetFilmRes) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilmRes.ProtoReflect.Descriptor instead.
func (*GetFilmRes) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *GetFilmRes) GetFilmId() int32 {
	if x != nil {
		return x.FilmId
	}
	return 0
}

func (x *GetFilmRes) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetFilmRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetFilmRes) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *GetFilmRes) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *GetFilmRes) GetGenres() string {
	if x != nil {
		return x.Genres
	}
	return ""
}

func (x *GetFilmRes) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\aproduct\",\n" +
	"\x12GetFilmDurationReq\x12\x16\n" +
	"\x06filmId\x18\x01 \x01(\x05R\x06filmId\"8\n" +
	"\x12GetFilmDurationRes\x12\"\n" +
	"\ffilmDuration\x18\x01 \x01(\tR\ffilmDuration\"(\n" +
	"\x10GetPriceOfFABReq\x12\x14\n" +
	"\x05fABId\x18\x01 \x01(\x05R\x05fABId\"(\n" +
	"\x10GetPriceOfFABRes\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x05R\x05price\"(\n" +
	"\x10CheckFABExistReq\x12\x14\n" +
	"\x05fABId\x18\x01 \x01(\x05R\x05fABId\"<\n" +
	"\x10CheckFABExistRes\x12(\n" +
	"\x0fresponseMessage\x18\x01 \x01(\tR\x0fresponseMessage\"$\n" +
	"\n" +
	"GetFilmReq\x12\x16\n" +
	"\x06filmId\x18\x01 \x01(\x05R\x06filmId\"\xd1\x01\n" +
	"\n" +
	"GetFilmRes\x12\x16\n" +
	"\x06filmId\x18\x01 \x01(\x05R\x06filmId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\frelease_date\x18\x04 \x01(\tR\vreleaseDate\x12\x1c\n" +
	"\tposterUrl\x18\x05 \x01(\tR\tposterUrl\x12\x16\n" +
	"\x06genres\x18\x06 \x01(\tR\x06genres\x12\x1a\n" +
	"\bduration\x18\a \x01(\tR\bduration2\x99\x02\n" +
	"\aProduct\x12K\n" +
	"\x0fGetFilmDuration\x12\x1b.product.GetFilmDurationReq\x1a\x1b.product.GetFilmDurationRes\x12E\n" +
	"\rGetPriceOfFAB\x12\x19.product.GetPriceOfFABReq\x1a\x19.product.GetPriceOfFABRes\x12E\n" +
	"\rCheckFABExist\x12\x19.product.CheckFABExistReq\x1a\x19.product.CheckFABExistRes\x123\n" +
	"\aGetFilm\x12\x13.product.GetFilmReq\x1a\x13.product.GetFilmResB\fZ\n" +
	"./;productb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_product_proto_goTypes = []any{
	(*GetFilmDurationReq)(nil), // 0: product.GetFilmDurationReq
	(*GetFilmDurationRes)(nil), // 1: product.GetFilmDurationRes
	(*GetPriceOfFABReq)(nil),   // 2: product.GetPriceOfFABReq
	(*GetPriceOfFABRes)(nil),   // 3: product.GetPriceOfFABRes
	(*CheckFABExistReq)(nil),   // 4: product.CheckFABExistReq
	(*CheckFABExistRes)(nil),   // 5: product.CheckFABExistRes
	(*GetFilmReq)(nil),         // 6: product.GetFilmReq
	(*GetFilmRes)(nil),         // 7: product.GetFilmRes
}
var file_product_proto_depIdxs = []int32{
	0, // 0: product.Product.GetFilmDuration:input_type -> product.GetFilmDurationReq
	2, // 1: product.Product.GetPriceOfFAB:input_type -> product.GetPriceOfFABReq
	4, // 2: product.Product.CheckFABExist:input_type -> product.CheckFABExistReq
	6, // 3: product.Product.GetFilm:input_type -> product.GetFilmReq
	1, // 4: product.Product.GetFilmDuration:output_type -> product.GetFilmDurationRes
	3, // 5: product.Product.GetPriceOfFAB:output_type -> product.GetPriceOfFABRes
	5, // 6: product.Product.CheckFABExist:output_type -> product.CheckFABExistRes
	7, // 7: product.Product.GetFilm:output_type -> product.GetFilmRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
