// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: showtime.proto

package showtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCinemaByShowtimeIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowtimeId    int32                  `protobuf:"varint,1,opt,name=showtimeId,proto3" json:"showtimeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCinemaByShowtimeIdReq) Reset() {
	*x = GetCinemaByShowtimeIdReq{}
	mi := &file_showtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCinemaByShowtimeIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCinemaByShowtimeIdReq) ProtoMessage() {}

func (x *GetCinemaByShowtimeIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_showtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCinemaByShowtimeIdReq.ProtoReflect.Descriptor instead.
func (*GetCinemaByShowtimeIdReq) Descriptor() ([]byte, []int) {
	return file_showtime_proto_rawDescGZIP(), []int{0}
}

func (x *GetCinemaByShowtimeIdReq) GetShowtimeId() int32 {
	if x != nil {
		return x.ShowtimeId
	}
	return 0
}

type GetCinemaByShowtimeIdRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCinemaByShowtimeIdRes) Reset() {
	*x = GetCinemaByShowtimeIdRes{}
	mi := &file_showtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCinemaByShowtimeIdRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCinemaByShowtimeIdRes) ProtoMessage() {}

func (x *GetCinemaByShowtimeIdRes) ProtoReflect() protoreflect.Message {
	mi := &file_showtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCinemaByShowtimeIdRes.ProtoReflect.Descriptor instead.
func (*GetCinemaByShowtimeIdRes) Descriptor() ([]byte, []int) {
	return file_showtime_proto_rawDescGZIP(), []int{1}
}

func (x *GetCinemaByShowtimeIdRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCinemaByShowtimeIdRes) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetCinemaByShowtimeIdRes) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

var File_showtime_proto protoreflect.FileDescriptor

const file_showtime_proto_rawDesc = "" +
	"\n" +
	"\x0eshowtime.proto\x12\bshowtime\":\n" +
	"\x18GetCinemaByShowtimeIdReq\x12\x1e\n" +
	"\n" +
	"showtimeId\x18\x01 \x01(\x05R\n" +
	"showtimeId\"^\n" +
	"\x18GetCinemaByShowtimeIdRes\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation2k\n" +
	"\bShowtime\x12_\n" +
	"\x15GetCinemaByShowtimeId\x12\".showtime.GetCinemaByShowtimeIdReq\x1a\".showtime.GetCinemaByShowtimeIdResB\rZ\v./;showtimeb\x06proto3"

var (
	file_showtime_proto_rawDescOnce sync.Once
	file_showtime_proto_rawDescData []byte
)

func file_showtime_proto_rawDescGZIP() []byte {
	file_showtime_proto_rawDescOnce.Do(func() {
		file_showtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_showtime_proto_rawDesc), len(file_showtime_proto_rawDesc)))
	})
	return file_showtime_proto_rawDescData
}

var file_showtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_showtime_proto_goTypes = []any{
	(*GetCinemaByShowtimeIdReq)(nil), // 0: showtime.GetCinemaByShowtimeIdReq
	(*GetCinemaByShowtimeIdRes)(nil), // 1: showtime.GetCinemaByShowtimeIdRes
}
var file_showtime_proto_depIdxs = []int32{
	0, // 0: showtime.Showtime.GetCinemaByShowtimeId:input_type -> showtime.GetCinemaByShowtimeIdReq
	1, // 1: showtime.Showtime.GetCinemaByShowtimeId:output_type -> showtime.GetCinemaByShowtimeIdRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_showtime_proto_init() }
func file_showtime_proto_init() {
	if File_showtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_showtime_proto_rawDesc), len(file_showtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_showtime_proto_goTypes,
		DependencyIndexes: file_showtime_proto_depIdxs,
		MessageInfos:      file_showtime_proto_msgTypes,
	}.Build()
	File_showtime_proto = out.File
	file_showtime_proto_goTypes = nil
	file_showtime_proto_depIdxs = nil
}
