// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: showtime.proto

package showtime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSomeInformationForTicketReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowtimeId    int32                  `protobuf:"varint,1,opt,name=showtimeId,proto3" json:"showtimeId,omitempty"`
	SeatIds       []int32                `protobuf:"varint,2,rep,packed,name=seatIds,proto3" json:"seatIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSomeInformationForTicketReq) Reset() {
	*x = GetSomeInformationForTicketReq{}
	mi := &file_showtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSomeInformationForTicketReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSomeInformationForTicketReq) ProtoMessage() {}

func (x *GetSomeInformationForTicketReq) ProtoReflect() protoreflect.Message {
	mi := &file_showtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSomeInformationForTicketReq.ProtoReflect.Descriptor instead.
func (*GetSomeInformationForTicketReq) Descriptor() ([]byte, []int) {
	return file_showtime_proto_rawDescGZIP(), []int{0}
}

func (x *GetSomeInformationForTicketReq) GetShowtimeId() int32 {
	if x != nil {
		return x.ShowtimeId
	}
	return 0
}

func (x *GetSomeInformationForTicketReq) GetSeatIds() []int32 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type GetSomeInformationForTicketRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CinemaName    string                 `protobuf:"bytes,1,opt,name=cinemaName,proto3" json:"cinemaName,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	RoomName      string                 `protobuf:"bytes,3,opt,name=roomName,proto3" json:"roomName,omitempty"`
	Seats         string                 `protobuf:"bytes,4,opt,name=seats,proto3" json:"seats,omitempty"`
	FilmId        int32                  `protobuf:"varint,5,opt,name=filmId,proto3" json:"filmId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSomeInformationForTicketRes) Reset() {
	*x = GetSomeInformationForTicketRes{}
	mi := &file_showtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSomeInformationForTicketRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSomeInformationForTicketRes) ProtoMessage() {}

func (x *GetSomeInformationForTicketRes) ProtoReflect() protoreflect.Message {
	mi := &file_showtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSomeInformationForTicketRes.ProtoReflect.Descriptor instead.
func (*GetSomeInformationForTicketRes) Descriptor() ([]byte, []int) {
	return file_showtime_proto_rawDescGZIP(), []int{1}
}

func (x *GetSomeInformationForTicketRes) GetCinemaName() string {
	if x != nil {
		return x.CinemaName
	}
	return ""
}

func (x *GetSomeInformationForTicketRes) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetSomeInformationForTicketRes) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *GetSomeInformationForTicketRes) GetSeats() string {
	if x != nil {
		return x.Seats
	}
	return ""
}

func (x *GetSomeInformationForTicketRes) GetFilmId() int32 {
	if x != nil {
		return x.FilmId
	}
	return 0
}

var File_showtime_proto protoreflect.FileDescriptor

const file_showtime_proto_rawDesc = "" +
	"\n" +
	"\x0eshowtime.proto\x12\bshowtime\"Z\n" +
	"\x1eGetSomeInformationForTicketReq\x12\x1e\n" +
	"\n" +
	"showtimeId\x18\x01 \x01(\x05R\n" +
	"showtimeId\x12\x18\n" +
	"\aseatIds\x18\x02 \x03(\x05R\aseatIds\"\x9e\x01\n" +
	"\x1eGetSomeInformationForTicketRes\x12\x1e\n" +
	"\n" +
	"cinemaName\x18\x01 \x01(\tR\n" +
	"cinemaName\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x1a\n" +
	"\broomName\x18\x03 \x01(\tR\broomName\x12\x14\n" +
	"\x05seats\x18\x04 \x01(\tR\x05seats\x12\x16\n" +
	"\x06filmId\x18\x05 \x01(\x05R\x06filmId2}\n" +
	"\bShowtime\x12q\n" +
	"\x1bGetSomeInformationForTicket\x12(.showtime.GetSomeInformationForTicketReq\x1a(.showtime.GetSomeInformationForTicketResB\rZ\v./;showtimeb\x06proto3"

var (
	file_showtime_proto_rawDescOnce sync.Once
	file_showtime_proto_rawDescData []byte
)

func file_showtime_proto_rawDescGZIP() []byte {
	file_showtime_proto_rawDescOnce.Do(func() {
		file_showtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_showtime_proto_rawDesc), len(file_showtime_proto_rawDesc)))
	})
	return file_showtime_proto_rawDescData
}

var file_showtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_showtime_proto_goTypes = []any{
	(*GetSomeInformationForTicketReq)(nil), // 0: showtime.GetSomeInformationForTicketReq
	(*GetSomeInformationForTicketRes)(nil), // 1: showtime.GetSomeInformationForTicketRes
}
var file_showtime_proto_depIdxs = []int32{
	0, // 0: showtime.Showtime.GetSomeInformationForTicket:input_type -> showtime.GetSomeInformationForTicketReq
	1, // 1: showtime.Showtime.GetSomeInformationForTicket:output_type -> showtime.GetSomeInformationForTicketRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_showtime_proto_init() }
func file_showtime_proto_init() {
	if File_showtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_showtime_proto_rawDesc), len(file_showtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_showtime_proto_goTypes,
		DependencyIndexes: file_showtime_proto_depIdxs,
		MessageInfos:      file_showtime_proto_msgTypes,
	}.Build()
	File_showtime_proto = out.File
	file_showtime_proto_goTypes = nil
	file_showtime_proto_depIdxs = nil
}
